# Generated by Django 4.0.2 on 2022-02-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
