# Generated by Django 4.0.2 on 2022-02-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='posted_images/'),
            preserve_default=False,
        ),
    ]
